### ISSUE TITLE
test_metadata_self_heal_on_open throwing unexpected traceback on failure

### ISSUE THREAD

**Issue by srijan-sivakumar** [gluster/redant#1000]
[2021-08-30 19:13:40,006] INFO  - Running test_metadata_self_heal_on_open_fd-rep
[2021-08-30 19:13:40,970] ERROR  - test_metadata_self_heal_on_open_fd-rep : 'TestCase' object has no attribute 'nodes'
[2021-08-30 19:13:40,970] ERROR  - test_metadata_self_heal_on_open_fd-rep : Traceback (most recent call last):
  File "/root/redant-test/redant/core/runner_thread.py", line 49, in run_thread
    self.terminate_test_func()
  File "./tests/functional/arbiter/test_metadata_self_heal_on_open_fd.py", line 34, in terminate
    for node in self.nodes:
AttributeError: 'TestCase' object has no attribute 'nodes'

**Comment by srijan-sivakumar** [comment]
@nik-redhat  this is the scenario when we define certain flag in the beginning of the test case but then the parent_run_test itself fails. Then we directly go to terminate without even defining the flag and hence the terminate also fails.

**Comment by nik-redhat** [comment]
Correct that's the reason I never keep anything outside the `try` block in the terminate. But, I guess this PR sneaked upon when I reviewed it :thinking: ..... anyways I think the way we are handling variables right now is totally fine. Just that we need to be a bit cautious while reviewing, in case someone misses out.

**Comment by srijan-sivakumar** [comment]
Cool. Then I'll push the changes by putting it inside the try-except block.
