### ISSUE TITLE
Failing sample test cases

### ISSUE THREAD

**Issue by srijan-sivakumar** [gluster/redant#1002]
The sample test cases are the reference implementations and should not fail. Will add the traceback seen in different TC failures.

**Comment by srijan-sivakumar** [comment]
In case of `test_brick_ops`

```python
[2021-08-30 23:26:25,087] ERROR  - Traceback (most recent call last):
  File "./tests/d_parent_test.py", line 87, in parent_run_test
    self.run_test(self.redant)
  File "./tests/example/sample_component/test_brick_ops.py", line 128, in run_test
    _, br_cmd = redant.form_brick_cmd(self.server_list,
  File "./common/ops/gluster_ops/brick_ops.py", line 449, in form_brick_cmd
    brick = unused_bricks[server_val][0]
IndexError: list index out of range
```

**Comment by srijan-sivakumar** [comment]
In case of `test_expand_shrink_volume`

```python
[2021-08-30 23:16:42,078] ERROR  - list index out of range
[2021-08-30 23:16:42,078] ERROR  - Traceback (most recent call last):
  File "./tests/d_parent_test.py", line 87, in parent_run_test
    self.run_test(self.redant)
  File "./tests/example/sample_component/test_expand_shrink_volume.py", line 24, in run_test
    ret = redant.expand_volume(self.server_list[0], self.vol_name,
  File "./common/ops/gluster_ops/volume_ops.py", line 502, in expand_volume
    bricks_cmd = self.form_brick_cmd_to_add_brick(node, volname,
  File "./common/ops/gluster_ops/brick_ops.py", line 597, in form_brick_cmd_to_add_brick
    _, bricks_cmd = self.form_brick_cmd(server_list, brick_root, volname,
  File "./common/ops/gluster_ops/brick_ops.py", line 449, in form_brick_cmd
    brick = unused_bricks[server_val][0]
IndexError: list index out of range
```

**Comment by srijan-sivakumar** [comment]
In case of `test_io_ops`

```python
[2021-08-30 22:44:52,842] ERROR  - Failure : python3: can't open file '/usr/share/redant/share/file_dir_ops.py': [Errno 2] No such file or directory

[2021-08-30 22:44:52,842] ERROR  - Traceback (most recent call last):
  File "./tests/nd_parent_test.py", line 56, in parent_run_test
    self.run_test(self.redant)
  File "./tests/example/sample_component/test_io.py", line 31, in run_test
    raise Exception(f"Failure : {ret_dict['error_msg']}")
Exception: Failure : python3: can't open file '/usr/share/redant/share/file_dir_ops.py': [Errno 2] No such file or directory
```

**Comment by srijan-sivakumar** [comment]
> In case of `test_io_ops`
> 
> ```python
> [2021-08-30 22:44:52,842] ERROR  - Failure : python3: can't open file '/usr/share/redant/share/file_dir_ops.py': [Errno 2] No such file or directory
> 
> [2021-08-30 22:44:52,842] ERROR  - Traceback (most recent call last):
>   File "./tests/nd_parent_test.py", line 56, in parent_run_test
>     self.run_test(self.redant)
>   File "./tests/example/sample_component/test_io.py", line 31, in run_test
>     raise Exception(f"Failure : {ret_dict['error_msg']}")
> Exception: Failure : python3: can't open file '/usr/share/redant/share/file_dir_ops.py': [Errno 2] No such file or directory
> ```

Drat. Wrong path given for the script. Should be `/usr/share/redant/script/file_dir_ops.py`
