### ISSUE TITLE
test_metadata_self_heal_on_open failing

### ISSUE THREAD

**Issue by schaffung** [gluster/redant#1004]
The test case is failing with the following traceback

```python
[2021-08-31 00:00:58,933] ERROR  - Expected username qa found geouser                                                                                                 
[2021-08-31 00:00:58,942] ERROR  - Traceback (most recent call last):           
  File "./tests/d_parent_test.py", line 87, in parent_run_test                  
    self.run_test(self.redant)                                                  
  File "./tests/functional/arbiter/test_metadata_self_heal_on_open_fd.py", line 163, in run_test
    self._verify_stat_info(nodes_to_check, test_file)                           
  File "./tests/functional/arbiter/test_metadata_self_heal_on_open_fd.py", line 54, in _verify_stat_info
    raise Exception(f"Expected username {self.user} "                           
Exception: Expected username qa found geouser
```

**Comment by nik-redhat** [comment]
The TC works fine on my env, can you try it out once on your env as well @srijan-sivakumar ?

```
Results for arbiter
Test nature : disruptive
TestName : test_metadata_self_heal_on_open_fd
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:01:05       |      NA     |
|   dist-rep  |     PASS    |        00:01:06       |      NA     |
|     arb     |     PASS    |        00:00:59       |      NA     |
|   dist-arb  |     PASS    |        00:01:20       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   4   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 04 minutes 46 seconds
✔ Tearing down successful.
```

**Comment by srijan-sivakumar** [comment]
Let me check on the CI env once a test run finishes..
