### ISSUE TITLE
Rexe failure for connection establishment not under try-except block

### ISSUE THREAD

**Issue by srijan-sivakumar** [gluster/redant#820]
There's a code section inside the rexe wherein we try to handle the reboot node scenario. I.e. if a command execution fails, we try to connect to that node and then again execute that command. Now this re-connection and re-execution lies in the except part, but they escape the exception handling. Causing problems when servers are un-reachable.

```python
try:
     _, stdout, stderr = self.node_dict[node].exec_command(cmd)
except Exception:
    # Reconnection to be done.
    self.connect_node(node)
    # On rebooting the node
    _, stdout, stderr = self.node_dict[node].exec_command(cmd)
```

Exception handling has to be put in place for the command `connect_node` and `exec_command`. but there's more to the story than just a try-except

**Comment by srijan-sivakumar** [comment]
on a finer observation...this is not the root cause...we need to handle the exception being returned wrt Paramiko.
If one were to check the environ during the initial connection, we use the following with the exception handling..

```python
        try:
            self.redant.establish_connection()
        except paramiko.ssh_exception.NoValidConnectionsError as e:
            error_handler(e, '''
            It seems one of the nodes is down.
            Message: {exc}.
            Check and run again.
            ''')
        except paramiko.ssh_exception.AuthenticationException as e:
            error_handler(e, """
            Authentication failed.
            Message: {exc}
            Check and run again.
            """)
        except timeout as e:
            error_handler(e, """
            Oops! There was a timeout connecting the servers.
            Message: {exc}
            Check and run again.
            """)
        except Exception as e:
            error_handler(e)
```

**Comment by srijan-sivakumar** [comment]
```console
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/redant/core/test_runner.py", line 119, in _nd_worker_process
    cls._run_test(job_data)
  File "/root/redant/core/test_runner.py", line 196, in _run_test
    runner_thread_obj = RunnerThread(tc_class, cls.param_obj, volume_type,
  File "/root/redant/core/runner_thread.py", line 21, in __init__
    self.tc_obj = tc_class(
  File "./tests/lazy_parent_test.py", line 28, in __init__
    self._configure(f"{mname}-{volume_type}", server_details,
  File "./tests/lazy_parent_test.py", line 39, in _configure
    self.redant.establish_connection()
  File "./common/rexe.py", line 59, in establish_connection
    self.connect_node(node, timeout)
  File "./common/rexe.py", line 46, in connect_node
    raise e
  File "./common/rexe.py", line 38, in connect_node
    node_ssh_client.connect(
  File "/root/redant-demo/lib/python3.8/site-packages/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/root/redant-demo/lib/python3.8/site-packages/paramiko/util.py", line 283, in retry_on_signal
    return function()
  File "/root/redant-demo/lib/python3.8/site-packages/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out
```

The actual issue....so in this case, a sample test case `test_glusterd_ops.py` was run and then one of the node was rebooted after Environment setup was a success. And we stumble across this exception wherein one of the multiprocessing thread is killed of due to the exception. Now if such a thing happens in a suite, other tests lined up for the said processing thread will be thrown out as the process had died.

**Comment by srijan-sivakumar** [comment]
On looking into the traceback, we see that the issue stems from `establish_connection`. This is invoked by __init__ in parent tests which inturn is invoked when we create an object of the test case using `tc_class`. On checking the code section in `runner_thread.py`, we can see that..

```python
        self.tc_obj = tc_class(
            mname, param_obj, volume_type, env_obj, log_path, log_level)
```

There is no try-except block over this invocation or even over the constructor activities in a parent test case. Hence when we see an exception thrown during the constructor invocation, things go for a toss. We need to protect this segment of code with exception handling and then appropriately populate the `test_stat` data structure so that result handler can take this into account.
