### ISSUE TITLE
Result file and terminate being skipped in CI

### ISSUE THREAD

**Issue by srijan-sivakumar** [gluster/redant#936]
It has been noticed lately that the result handling as well as the terminate is being skipped in the CI run. There are no exceptions being thrown and errors seen in the logs or stdout. The test cases being run are in range of 180 cases. 

Important point to note is that if the suite is run for just a single component like `glusterfind`, the results and terminate are being handled properly.

The suspected area of code is xls. When xls file is being created and data from in-memory is being stored.

**Comment by srijan-sivakumar** [comment]
```python
Traceback (most recent call last):
  File "./core/redant_main.py", line 151, in <module>
    main()
  File "./core/redant_main.py", line 142, in main
    handle_results(result_queue, total_time, logger_obj,
  File "/root/redant-test/redant/core/result_handler.py", line 402, in handle_results
    _data_to_xls(statDict, resultDict, filePath, totalTime, logger)
  File "/root/redant-test/redant/core/result_handler.py", line 306, in _data_to_xls
    tR.write(row, 5, volData['skipReason'])
  File "/root/redant-test/rvirt/lib/python3.8/site-packages/xlwt/Worksheet.py", line 1088, in write
    self.row(r).write(c, label, style)
  File "/root/redant-test/rvirt/lib/python3.8/site-packages/xlwt/Row.py", line 254, in write
    raise Exception("Unexpected data type %r" % type(label))
Exception: Unexpected data type <class 'Exception'>
```

**Comment by srijan-sivakumar** [comment]
The exception is being thrown because the value being assigned to SKIP_REASON in parent tests is of type <class 'Exception'> and it is these values which we are pushing as skip reason inside the spreadsheet using a  function which expects strings.

Now, this is just one instance wherein an exception was not even expected in the code section in initial stages of project but with time the code logic was modified in such a manner that the exception has been introduced. This implies redant needs to be robust to catch exception which are not even envisaged right now and due to some reason, the exception handling is not put in place in future causing costly errors and disruptions. This means a sort of catch all exception over the main() call in the `redant_main`. Secondly, we need to capture it in a file. Keeping in mind that even logging module can fail plus redant can fail even before logging module has been instantiated, we still need to capture the traceback and error. The path determined for this purpose needs to be common and the file naming generic, for example path can be `/tmp/redant` and file name `redant-<timestamp>`, this file's presence needs to be checked if there are any issues with a suite run as this can catch any exceptions not thought of before.
